name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  CONTAINS: ${{ toJson(contains(join(github.event.commits.*.message, ' '), '#skip')) }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build:ui
      - name: Build failure
        uses: sebastianpopp/discord-action@releases/v2
        if: ${{ failure() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: Build failed. Commit https://github.com/xtanyx/CI_CD_phonebook/commit/${{ github.sha }} broke the build
      - name: test
        run: cd ./frontend && npm test
      - name: Preparing dependencies for playwright
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: deploy
        run: flyctl deploy --remote-only
        if: ${{ github.event_name == 'push' && env.CONTAINS != 'true' }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Deploy success
        uses: sebastianpopp/discord-action@releases/v2
        if: ${{ github.event_name == 'push' && env.CONTAINS != 'true' && success() }}
        with:
          message: A new version of phonebook deployed!
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        if: ${{ github.event_name == 'push' && env.CONTAINS != 'true'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: 0.0.1
          DEFAULT_BUMP: patch
          WITH_V: true